# Generated by Django 2.1.2 on 2018-10-21 21:35

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bestiary', '0005_auto_20180814_0443'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreatureInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('game_id', models.IntegerField(null=True)),
                ('rank', models.IntegerField()),
                ('level', models.IntegerField()),
                ('creature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestiary.Creature')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Account')),
            ],
        ),
        migrations.CreateModel(
            name='FriendRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GlyphInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('game_id', models.IntegerField(null=True)),
                ('type', models.IntegerField(choices=[(1, 'Vitality'), (2, 'Strength'), (3, 'Frenzy'), (4, 'Defense'), (5, 'Haste'), (6, 'Precision'), (7, 'Destruction'), (8, 'Endurance'), (9, 'Life Steal'), (10, 'Appeasement'), (11, 'Meditation'), (12, 'Immunity')])),
                ('rarity', models.IntegerField(choices=[(1, 'Common'), (2, 'Uncommon'), (3, 'Rare'), (4, 'Epic'), (5, 'Legendary'), (6, 'Dark')])),
                ('shape', models.IntegerField(choices=[(1, 'Hex'), (2, 'Leaf'), (3, 'Square')])),
                ('stars', models.IntegerField()),
                ('level', models.IntegerField()),
                ('stats', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('creature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.CreatureInstance')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy', models.IntegerField(choices=[(1, 'Public'), (2, 'Friends Only'), (3, 'Private')], default=3)),
                ('preferences', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('friends', models.ManyToManyField(through='profiles.FriendRelationship', to='profiles.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, help_text='<a href="https://daringfireball.net/projects/markdown/syntax" target="_blank">Markdown syntax</a> enabled', null=True)),
                ('dungeon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bestiary.Dungeon')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bestiary.Level')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
                ('roster', models.ManyToManyField(to='profiles.CreatureInstance')),
            ],
        ),
        migrations.AddField(
            model_name='friendrelationship',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='friendrelationship',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='profiles.Profile'),
        ),
    ]
