# Generated by Django 2.1.2 on 2018-10-20 16:39

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bestiary', '0005_auto_20180814_0443'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatureInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('game_id', models.IntegerField(null=True)),
                ('rank', models.IntegerField()),
                ('level', models.IntegerField()),
                ('creature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestiary.Creature')),
            ],
        ),
        migrations.CreateModel(
            name='GlyphInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('game_id', models.IntegerField(null=True)),
                ('type', models.IntegerField(choices=[(1, 'Vitality'), (2, 'Strength'), (3, 'Frenzy'), (4, 'Defense'), (5, 'Haste'), (6, 'Precision'), (7, 'Destruction'), (8, 'Endurance'), (9, 'Life Steal'), (10, 'Appeasement'), (11, 'Meditation'), (12, 'Immunity')])),
                ('rarity', models.IntegerField(choices=[(1, 'Common'), (2, 'Uncommon'), (3, 'Rare'), (4, 'Epic'), (5, 'Legendary'), (6, 'Dark')])),
                ('stars', models.IntegerField()),
                ('level', models.IntegerField()),
                ('stats', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('creature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.CreatureInstance')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='glyphinstance',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='creatureinstance',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile'),
        ),
    ]
