# Generated by Django 2.1.2 on 2018-10-20 18:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0005_auto_20180814_0443'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, help_text='<a href="https://daringfireball.net/projects/markdown/syntax" target="_blank">Markdown syntax</a> enabled', null=True)),
                ('dungeon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bestiary.Dungeon')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bestiary.Level')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
                ('roster', models.ManyToManyField(to='profiles.CreatureInstance')),
            ],
        ),
    ]
