# Generated by Django 2.0.6 on 2018-06-14 20:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('playable', models.BooleanField()),
                ('summonable', models.BooleanField()),
                ('inMenagerie', models.BooleanField()),
                ('rank', models.IntegerField()),
                ('archetype', models.CharField(choices=[('attacker', 'Attacker'), ('defender', 'Defender'), ('saboteur', 'Saboteur'), ('support', 'Support')], max_length=15)),
                ('element', models.CharField(choices=[('fire', 'Fire'), ('water', 'Water'), ('air', 'Air'), ('earth', 'Earth'), ('light', 'Light'), ('dark', 'Dark')], max_length=10)),
                ('group', models.CharField(choices=[('bad', 'Bad'), ('avg', 'Average'), ('good', 'Good'), ('veryGood', 'Very Good'), ('outstanding', 'Outstanding')], max_length=15)),
                ('subgroup', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, size=None)),
                ('lore', models.TextField(blank=True, default='')),
                ('creatureType', models.CharField(max_length=50)),
                ('trackingName', models.CharField(max_length=50)),
                ('hp', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('criticalChance', models.IntegerField()),
                ('criticalDamage', models.IntegerField()),
                ('accuracy', models.FloatField()),
                ('resistance', models.FloatField()),
                ('initialSpeed', models.IntegerField()),
                ('speed', models.FloatField()),
            ],
        ),
    ]
