# Generated by Django 2.0.6 on 2018-06-14 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creature',
            options={'ordering': ['rank', 'name']},
        ),
    ]
