# Generated by Django 2.0.7 on 2018-07-24 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boss',
            name='wave',
        ),
        migrations.AlterUniqueTogether(
            name='bossspell',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='bossspell',
            name='creature',
        ),
        migrations.AlterUniqueTogether(
            name='bossspelleffect',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='bossspelleffect',
            name='spell',
        ),
        migrations.RemoveField(
            model_name='enemy',
            name='miniboss',
        ),
        migrations.AddField(
            model_name='enemy',
            name='boss_type',
            field=models.CharField(blank=True, choices=[('miniBoss', 'Miniboss'), ('boss', 'Boss')], max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Boss',
        ),
        migrations.DeleteModel(
            name='BossSpell',
        ),
        migrations.DeleteModel(
            name='BossSpellEffect',
        ),
    ]
