# Generated by Django 2.0.6 on 2018-06-28 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='evolvesFrom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolvesTo', to='bestiary.Creature'),
        ),
    ]
