# Generated by Django 2.0.6 on 2018-06-15 06:51

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0002_auto_20180614_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatureSpell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=50)),
                ('params', models.TextField(blank=True, default='')),
                ('creature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestiary.Creature')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=35)),
                ('image', models.CharField(max_length=50)),
                ('turns', models.IntegerField(blank=True, null=True)),
                ('passive', models.BooleanField(default=False)),
                ('passiveTrigger', models.CharField(blank=True, default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SpellEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('effect', models.CharField(max_length=30)),
                ('target', models.CharField(choices=[('one', 'One'), ('all', 'All'), ('self', 'Self'), ('one_minus_self', 'One (excluding self)'), ('all_minus_self', 'All (excluding self)'), ('all_minus_one', 'All (minus one)'), ('random_dead', 'Random Dead')], max_length=20)),
                ('condition', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('attackCriticalLaunched', 'Critical Hit'), ('targetHasDebuff', 'Target Has Debuff'), ('selfHpAbove', 'Own HP Above Threshold'), ('targetHpEquals', 'Target HP Equals Threshold'), ('targetHpAbove', 'Target HP Above Threshold'), ('targetHpBelow', 'Target HP Below Threshold'), ('link', 'Link')], default='', max_length=30), blank=True, size=None)),
                ('permanent', models.NullBooleanField()),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestiary.Spell')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SpellUpgrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('game_id', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('is_percentage', models.BooleanField()),
                ('attribute', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=150)),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestiary.Spell')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='creaturespell',
            name='spell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestiary.Spell'),
        ),
        migrations.AddField(
            model_name='creature',
            name='spells',
            field=models.ManyToManyField(through='bestiary.CreatureSpell', to='bestiary.Spell'),
        ),
    ]
