# Generated by Django 2.0.7 on 2018-07-25 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0002_auto_20180724_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='group',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('bad', 'Bad'), ('avg', 'Average'), ('good', 'Good'), ('veryGood', 'Very Good'), ('outstanding', 'Outstanding')], max_length=15),
        ),
    ]
