# Generated by Django 2.0.6 on 2018-06-28 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0002_creature_evolvesfrom'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='evoAttack',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creature',
            name='evoCriticalChance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creature',
            name='evoDefense',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creature',
            name='evoHp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creature',
            name='maxLvlAttack',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creature',
            name='maxLvlDefense',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creature',
            name='maxLvlHp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
