# Generated by Django 2.0.7 on 2018-07-31 17:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0003_auto_20180725_0412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dropgroup',
            name='level',
        ),
        migrations.RemoveField(
            model_name='drops',
            name='group',
        ),
        migrations.AddField(
            model_name='level',
            name='rewards',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='level',
            name='rewards_instant',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, help_text='Rewards when using an Instant Ticket'),
        ),
        migrations.AlterField(
            model_name='level',
            name='slots',
            field=models.IntegerField(help_text='Number of creatures allowed to bring'),
        ),
        migrations.DeleteModel(
            name='DropGroup',
        ),
        migrations.DeleteModel(
            name='Drops',
        ),
    ]
