# Generated by Django 2.0.6 on 2018-06-28 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0004_spell_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creature',
            name='evolvesFrom',
        ),
        migrations.AddField(
            model_name='creature',
            name='evolvesTo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolvesFrom', to='bestiary.Creature'),
        ),
    ]
