# Generated by Django 2.1 on 2018-08-14 04:43

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0004_auto_20180731_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dungeon',
            name='days_available',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='dungeon',
            name='months_available',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='enemyspelleffect',
            name='condition',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('attackCriticalLaunched', 'Critical Hit'), ('targetHasDebuff', 'Target Has Debuff'), ('selfHpAbove', 'Own HP Above Threshold'), ('targetHpEquals', 'Target HP Equals Threshold'), ('targetHpAbove', 'Target HP Above Threshold'), ('targetHpBelow', 'Target HP Below Threshold'), ('link', 'Link')], default='', max_length=30), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='enemyspelleffect',
            name='params',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='level',
            name='rewards',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='level',
            name='rewards_instant',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='Rewards when using an Instant Ticket'),
        ),
        migrations.AlterField(
            model_name='spelleffect',
            name='condition',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('attackCriticalLaunched', 'Critical Hit'), ('targetHasDebuff', 'Target Has Debuff'), ('selfHpAbove', 'Own HP Above Threshold'), ('targetHpEquals', 'Target HP Equals Threshold'), ('targetHpAbove', 'Target HP Above Threshold'), ('targetHpBelow', 'Target HP Below Threshold'), ('link', 'Link')], default='', max_length=30), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='spelleffect',
            name='params',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
