# Generated by Django 2.0.6 on 2018-07-01 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0005_auto_20180628_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
