# Generated by Django 2.0.6 on 2018-07-01 02:55

from django.db import migrations
from django.utils.text import slugify


def resave_all(apps, schema_editor):
    # Re-save each creature to create the slug
    Creature = apps.get_model('bestiary', 'Creature')
    for c in Creature.objects.all():
        c.slug = slugify(f'{c.pk}-{c.name}-{c.element}')
        c.save()


def do_nothing(apps, schema_editor):
    # Migrating backwards will just remove the slug field, so no actual operation is required
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0006_creature_slug'),
    ]

    operations = [
        migrations.RunPython(resave_all, do_nothing)
    ]
