# Generated by Django 2.0.6 on 2018-07-11 07:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0007_auto_20180701_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='spelleffect',
            name='probability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spelleffect',
            name='condition',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('attackCriticalLaunched', 'Critical Hit'), ('targetHasDebuff', 'Target Has Debuff'), ('selfHpAbove', 'Own HP Above Threshold'), ('targetHpEquals', 'Target HP Equals Threshold'), ('targetHpAbove', 'Target HP Above Threshold'), ('targetHpBelow', 'Target HP Below Threshold'), ('link', 'Link')], default='', max_length=30), blank=True, default=[], size=None),
        ),
    ]
