# Generated by Django 2.0.6 on 2018-07-14 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0009_auto_20180714_0236'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='spell',
            unique_together={('creature', 'slot')},
        ),
    ]
