# Generated by Django 2.0.6 on 2018-07-14 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0010_auto_20180714_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell',
            name='order',
        ),
    ]
