# Generated by Django 2.0.6 on 2018-07-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0011_remove_spell_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wave',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
